<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
<title>工程FMEA管理系统</title>
<link href="Includes/Style.css" rel="stylesheet" type="text/css">

<link rel = "stylesheet" href="http://172.29.2.27/resources/autogenerated/qlik-styles.css">
<script src="http://172.29.2.27/resources/assets/external/requirejs/require.js"></script>
    <script>
        var config = {
            host: '172.29.2.27',
            prefix: '/',
            port: 80,
            isSecure: false
        };
        require.config( {
            baseUrl: ( config.isSecure? "https://" : "http://" ) + config.host + (config.port? ":" + config.port: "") + config.prefix + "resources"
        });
        var qlikApps = [];

        require(["js/qlik"], function ( qlik ){
            qlik.setOnError(function(error) {
                alert(error.message);
            });
            function attach(elem){
                var appid = elem.dataset.qlikAppid;
                var objid = elem.dataset.qlikObjid;
                var app = qlikApps[appid];
                if (!app){
                    app = qlik.openApp(appid, config);
                    qlikApps[appid] = app;
                }
                app.getObject(elem, objid);
            }
            var elems = document.getElementsByClassName('qlik-embed');
            var ix = 0;
            for (; ix < elems.length; ++ix){
                attach(elems[ix]);
            }
        });
    </script>

    <!--Static height to show qlik object, this can be modified.-->
    <style>
        .qlik-embed {
            height: 300px;
        }
    </style>

</head>
<body>
<form>
 <button type='button' onclick="qlikApps['6c8d0ad7-19b0-4aac-a35c-ea1647789ac2'].clearAll()"> Clear All </button> 
 <button type='button' onclick="qlikApps['6c8d0ad7-19b0-4aac-a35c-ea1647789ac2'].back()"    > Back      </button> 
 <div class="qlik-embed" data-qlik-objid="EtQJB" data-qlik-appid="6c8d0ad7-19b0-4aac-a35c-ea1647789ac2">heed</div>
 </form> 
</body>
</html>